### ISSUE TITLE
superfluous line

### ISSUE THREAD

**Issue by g-sam** [Kata-Martagon/Stopwatch-NogaMatt#19]
https://github.com/Kata-Martagon/Stopwatch-NogaMatt/blob/master/particles.js#L156
this line changes nothing (I think)

**Comment by g-sam** [comment]
https://github.com/Kata-Martagon/Stopwatch-NogaMatt/blob/master/particles.js#L153
this line is also superfluous

**Comment by matthewiiv** [comment]
That's right, they were artifacts from before I added the spread function
